# Generated by Django 5.0.6 on 2024-08-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='user_sensitive',
            field=models.BooleanField(default=False),
        ),
    ]
