# Generated by Django 5.0.6 on 2024-08-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_postmedia_user_sensitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='sensitivity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
    ]
