# Generated by Django 5.0.6 on 2024-08-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Indigenous', 'Indigenous'), ('Others', 'Others')], max_length=20, verbose_name='Religion'),
        ),
    ]
